version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./env.dev.js:/usr/share/nginx/html/env.js:ro
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - app-network
    
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge