apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init-job
  namespace: grocery-app
spec:
  backoffLimit: 5
  template:
    spec:
      containers:
        - name: init
          image: mongo:6
          command: ["bash", "-c"]
          args:
            - |
              echo "Waiting for MongoDB to become available..."
              until mongosh --host mongo-0.mongo.grocery-app.svc.cluster.local --eval "db.hello().isWritablePrimary || db.hello().secondary" > /dev/null 2>&1; do
                echo "Waiting..."
                sleep 2
              done
              echo "Initializing replica set..."
              mongosh --host mongo-0.mongo.grocery-app.svc.cluster.local <<EOF
              rs.initiate({
                _id: "rs0",
                members: [
                  { _id: 0, host: "mongo-0.mongo.grocery-app.svc.cluster.local:27017" },
                  { _id: 1, host: "mongo-1.mongo.grocery-app.svc.cluster.local:27017" },
                  { _id: 2, host: "mongo-2.mongo.grocery-app.svc.cluster.local:27017" }
                ]
              })
              EOF
      restartPolicy: OnFailure
